### ISSUE TITLE
If more tickets are sold than the limit, the ticket sale will stay open

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-frontend#241]
https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/app/elements/lancie-ticket-page/lancie-ticket-block.html#L221

Let's say the limit is 10 en for some magical reason 11 are sold, the frontend will still show the tickets as available.

**Comment by martijnjanssen** [comment]
I have no clue what this issue is referring to, this has to be tested, but not now. As a new ticket page is currently being made. The link has changed to [this](https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/src/lancie-ticket-page/lancie-ticket-block.html#L221) due to moving the files around.
