### ISSUE TITLE
Dialogs in order process perceived as annoying

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#409]
We currently have 3 intercepts in the Order proces

1. Login
2. Profile check
3. Terms and conditions

Each dialog requires the user to click the same button again, which is perceived as annoying and slow. We should streamline this better by chaining them together, without the need to click the same button in between.

**Comment by martijnjanssen** [comment]
- We could remove the terms and conditions and make it a checkbox that needs to be checked before ordering, adding a link to the terms and conditions will still make it accessible.
- Trigger the profile check directly after logging in

As for the login, users can't have it both ways, logging in is something that they will have to do.

**Comment by skamoen** [comment]
It's not about the number of dialogs, it's about the fact they have to click the continue/checkout button 4 times in the worst case.

**Comment by martijnjanssen** [comment]
Correct, I agree. We have to find a good solution for this.

This is not very easy though, since the login dialog is placed in the login-check and the other two dialogs are placed in the lancie-ticket-basket. A solution is to give a function on the login-dialog event to call after the user is done logging in. This is just one of the things we could do.
